name: Deploy to Dev

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{vars.HEROKU_APP_NAME}}
          heroku_email: ${{vars.HEROKU_EMAIL}}
      - name: Set Heroku environment variables
        run: |
            heroku config:set DATABASE_HOST=${{ secrets.DATABASE_HOST }} \
            DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} \
            DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
            DATABASE_NAME=${{ secrets.DATABASE_NAME }} \
            ENV=prod
            --app ${{ vars.HEROKU_APP_NAME }}
          # usedocker: true